### ISSUE TITLE
When creating a new object form, modal doesn't disappear after clicking. 

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#110]
Create new form
click object
"metadata vs object" modal doesn't disappear. Clicking one of them again appends new elements to the form.

**Comment by ddavisgraphics** [comment]
Fixed.  This was from a different issue, which made the event handler loop and as a result no other events were being read.  Also during this time I fixed an issue with the click handler on the icon for delete.  Instead of keeping it a click handler I tracked the event target of the LI.  That eliminated one event handler to help with speed / performance.
