### ISSUE TITLE
When the files don't exist, get errors. Need to check that the file exists before ... 

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#150]
[Mon Feb 08 15:39:23 2016] [error] [client 10.0.2.2] filesize(): stat failed for /home/mfcs.lib.wvu.edu/data/archives/mfcs/7/7/2/6/c/f/f/d/9/c/2/a/4/3/4/f/a/f/f/5/5/f/c/0/0/4/d/d/b/9/7/a/7726cffd-9c2a-434f-aff5-5fc004ddb97a/am4050_card_1990_c.tif at 379:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55
[Mon Feb 08 15:39:23 2016] [error] [client 10.0.2.2] finfo::file(/home/mfcs.lib.wvu.edu/data/archives/mfcs/7/7/2/6/c/f/f/d/9/c/2/a/4/3/4/f/a/f/f/5/5/f/c/0/0/4/d/d/b/9/7/a/7726cffd-9c2a-434f-aff5-5fc004ddb97a/am4050_card_1990_c.tif): failed to open stream: No such file or directory at 380:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55
[Mon Feb 08 15:39:23 2016] [error] [client 10.0.2.2] Undefined offset: -9223372036854775808 at 334:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55
[Mon Feb 08 15:39:23 2016] [error] [client 10.0.2.2] Undefined index: convertAudio at 453:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55
[Mon Feb 08 15:39:23 2016] [error] [client 10.0.2.2] Undefined index: convertVideo at 460:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55
[Mon Feb 08 15:39:23 2016] [error] [client 10.0.2.2] Undefined index: videothumbnail at 467:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55

**Comment by ddavisgraphics** [comment]
[Mon Feb 08 15:39:23 2016] [error] [client 10.0.2.2] Undefined index: convertAudio at 453:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55
[Mon Feb 08 15:39:23 2016] [error] [client 10.0.2.2] Undefined index: convertVideo at 460:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55
[Mon Feb 08 15:39:23 2016] [error] [client 10.0.2.2] Undefined index: videothumbnail at 467:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55 

These were fixed by making sure that they are set before continuing to bool.

**Comment by ddavisgraphics** [comment]
home/mfcs.lib.wvu.edu/data/archives/mfcs/7/7/2/6/c/f/f/d/9/c/2/a/4/3/4/f/a/f/f/5/5/f/c/0/0/4/d/d/b/9/7/a/7726cffd-9c2a-434f-aff5-5fc004ddb97a/am4050_card_1990_c.tif at 379:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55
[Mon Feb 08 15:39:23 2016] [error] [client 10.0.2.2] finfo::file(/home/mfcs.lib.wvu.edu/data/archives/mfcs/7/7/2/6/c/f/f/d/9/c/2/a/4/3/4/f/a/f/f/5/5/f/c/0/0/4/d/d/b/9/7/a/7726cffd-9c2a-434f-aff5-5fc004ddb97a/am4050_card_1990_c.tif): failed to open stream: No such file or directory at 380:/vagrant/public_html/includes/classes/files.php, referer: http://localhost:8080/dataView/list.php?listType=form&formID=55 


This was fixed by adding directory seperator

**Comment by ddavisgraphics** [comment]
Other issue is no longer coming up.
